---
name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '**.md'

jobs:
  test:
    name: Test Representer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t python-representer .
      
      - name: (TEMP) Verify tooling-webserver
        run: docker run --rm --entrypoint "/bin/bash" python-representer which tooling-webserver && ls -l `which tooling-webserver`
          
      - name: Run Tests
        run: docker run --entrypoint "pytest" python-representer
